image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose

build:
  stage: build
  script:
  - docker-compose -f $CI_PROJECT_DIR/support/build/docker-compose.yml up

test1:
 stage: test
 script: 
   - "./support/tests/test.sh"
