services:
  - docker
  
before_script:
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose -f $CI_PROJECT_DIR/support/build/docker-compose.yml up

#setup preside app

test1:
 stage: test
 script: 
   - "./support/tests/test.sh"
    
after_script:
  - docker-compose down
